### ISSUE TITLE
Can I position a Visual Studio window same as any other window?

### ISSUE THREAD

**Issue by jbuedel** [hoppfrosch/WindowPadX#12]
Once I detach a window from Visual Studio, I'd like to be able to move it around same as I can with any other application. Note that the Windows + Arrow hot keys work on the detached window as expected, but the WindowPadX commands do not. 

I'm pretty sure this worked in the original WindowPad.  Is this possible with WindowPadX?

**Comment by SqlBarbarian** [comment]
Visual studio windows work for me. 
However, anything with devexpress components (i believe), ie floating windows, don't work correctly. They don't seem to recognize the window as unique and only move a few pixels when resizing.

**Comment by jbuedel** [comment]
At some point since I posted this it started working again.
